### ISSUE TITLE
[BUG] Using "Dynamic Multi File" Field (Dropzone) causes Exception

### ISSUE THREAD

**Issue by akno77** [dachcom-digital/pimcore-formbuilder#350] opened 2022-09-07 15:03 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes

If I use a "Dynamic Multi File" Field with Dropzone it causes an Excpetion in the frontend:

`FormBuilderBundle\Form\Type\DynamicMultiFile\DropZoneType::__construct(): Argument #1 ($translator) must be of type Pimcore\Translation\Translator, Symfony\Component\Translation\DataCollectorTranslator given, called in /app/var/cache/dev/ContainerWxLuP67/getDropZoneTypeService.php on line 24 File: /app/vendor/dachcom-digital/formbuilder/src/FormBuilderBundle/Form/Type/DynamicMultiFile/DropZoneType.php Line: 16`

Pimcore v10.5.5
Formbuilder v4.1.2

**Comment by solverat** [comment] 2022-11-16 16:29
@akno77 is this still an issue? I'm not able to reproduce this.

**Comment by solverat** [comment] 2022-11-18 23:51
Feel free to give some feedback if this is still relevant. I'm going to close this for now since it's reproducible for us and also drop zone tests are passing.

**Closed by solverat** 2022-11-18 23:51 UTC
