### ISSUE TITLE
[bug] Dynamic Choice Type choices should not be repeated in preferred choices

### ISSUE THREAD

**Issue by ceefour** [dachcom-digital/pimcore-formbuilder#204] opened 2019-12-01 12:37 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Dynamic choice type repeats choices inside the "preferred choices" list:

![image](https://user-images.githubusercontent.com/24123/69913992-6cf3d300-1471-11ea-9cb4-beae6ee6f6f6.png)

### Simple example:

```
<?php

namespace AppBundle\Services;

use FormBuilderBundle\Form\ChoiceBuilderInterface;
use Symfony\Component\Form\FormBuilderInterface;

class StateChoices implements ChoiceBuilderInterface
{
  protected $builder;

  public function setFormBuilder(FormBuilderInterface $builder)
  {
    $this->builder = $builder;
  }

  public function getList() {
    return ['something' => 'ohyes'];
  }

}
```

result:

![image](https://user-images.githubusercontent.com/24123/69914001-8bf26500-1471-11ea-820c-0b756fac3d5c.png)

### Even if we set preferred choices:

![image](https://user-images.githubusercontent.com/24123/69914006-adebe780-1471-11ea-9e35-446931d13e02.png)

Will result in:

![image](https://user-images.githubusercontent.com/24123/69914009-bb08d680-1471-11ea-917b-70170c9f82cc.png)

Note: that this specific case of preferred choices may be expected behavior sometimes.

### AdvancedChoiceBuilderInterface also has a bug

Using `AdvancedChoiceBuilderInterface::getPreferredChoices($element, $key, $index)` has no effect. It seems to be ignored.

### Expected behavior

If "preferred choices" is empty (default), there should be no preferred choices.

Related to #189 #72.

### Workaround

Put something meaningless/unknown in Base > Preferred Choices, e.g. `-`.

**Comment by solverat** [comment] 2020-02-03 16:17
Not reproducable, seems to be fixed with https://github.com/dachcom-digital/pimcore-formbuilder/commit/42b1c30dc1a957ee39f62dd5d47ee67953b21a63.

BTW: In my AdvancedChoiceBuilder it worked with:

```php
public function getPreferredChoices($element, $key, $value)
{
     return $value == 'value_3';
}
```

**Closed by solverat** 2020-02-03 16:17 UTC
